### ISSUE TITLE
Smart Rules

### ISSUE THREAD

**Issue by gusinacio** [gocachebr/terraform-provider-gocache#1]
When will smart rules resource be available? It's currently on the example but there's no resource yet.

**Comment by mockthebear** [comment]
Hello @flametuner! 
The resource will be available within a month, we're already working on it

**Comment by mockthebear** [comment]
Good news @flametuner we just released the smart rules module! 
Hope it fits your needs also don't hesitate to communicate to us if you find any other issue.
