### ISSUE TITLE
json: cannot unmarshal object after successfully created record 

### ISSUE THREAD

**Issue by toketas** [gocachebr/terraform-provider-gocache#4]
## Version
0.3.1

## Steps to reproduce

```
provider "gocache" {
  api_token = "xxx"
}

resource "gocache_record" "aa" {
  domain = "domain.com"

  name = "test"
  type = "A"
  content = "33.100.100.100"
  ttl = 123
  proxied = false
  priority = 1
}
```

terraform apply -> success
terraform plan

![image](https://user-images.githubusercontent.com/3934190/153008450-784e84d4-76e8-43f2-9765-716d624acc3f.png)

**Comment by mockthebear** [comment]
Thanks @[toketas](https://github.com/toketas) for opening the issue! We already sent a fix for that in the commit  ed7f4800117ea0cec45819f50dd5619feff9b399
